server:
  address: 127.0.0.1

spring:
  application:
    name: csc-x-tool
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  mvc:
    problemdetails:
      enabled: false

logging:
  level:
    org.springframework: INFO
